### ISSUE TITLE
Topics for Discussion

### ISSUE THREAD

**Issue by fifoosid** [SAP/ui5-webcomponents#2347]
### 1.0.0 TODOs
- [x] Review and Complete [Breaking Changes](https://github.com/SAP/ui5-webcomponents/pulls?q=is%3Apr+is%3Aopen+label%3A%22BREAKING+CHANGE%22)
- [x] Review "base" package API
- [x] Custom Theming
-> create own ThemeDesigner app/tool (based on [less-openui5](https://github.com/SAP/less-openui5)) and remove the section https://github.com/SAP/ui5-webcomponents/pull/3717 https://github.com/SAP/ui5-webcomponents/issues/3718.
- [x] RTL issue: https://github.com/SAP/ui5-webcomponents/pull/3657
- [x] How to remain compatible in UI5 with the "retrofit" after we release new major version of UI5 Web Components
-> We must have compatible APIs of the Control Wrappers, so (1) either stick to old UI5 Web Components version,
or (2) adapt to newer version, keeping the Control Wrappers APIs compatible.

### TODOs
- [x] Should we rename the "retrofit" GitHub project
-> yes
- [x] Performance [issue](https://github.com/SAP/ui5-webcomponents/issues/3614) with RTL (not critical for 1.0.0)
- [x] Alignment issue between Button, Link, Input and standard HTML elements
- [x] Check side effects after changes in the "base" - https://github.com/SAP/ui5-webcomponents/pull/3677
- [x] Document app development related APIs from the "base"
- [x] Playground documentation section order (decide on Thursday 26 Aug)
- [x] Typescript definitions for "base" - https://github.com/SAP/ui5-webcomponents/pull/3653
- [x] How to make the Control Wrappers available separately, otherwise the users will get whole library, when single control is actually needed (like the BardCodeScanner)?
- [x] Discuss advanced Table features (like sap.ui.table.Table), we already have requirements from MDK and SAP Ariba
-> we sent a mail to the MDK colleagues that we will be able to work on these features after the official release.

###  Other

- [x] https://github.com/SAP/ui5-webcomponents/pull/3495
- [x] Event bubbling
if you use the UI5 WC Input in a composition (higher level component), then it is not possible to listen to the events of the Input component on the composition level.
https://github.com/SAP/ui5-webcomponents/issues/2329
- [x] Rework all components to not use _id
https://github.com/SAP/ui5-webcomponents/issues/1695
- [x] Re-iterate on event marking
https://github.com/SAP/ui5-webcomponents/issues/1489
- [ ] Create stable IDs for all components
https://github.com/SAP/ui5-webcomponents/issues/2361
- [x] Run tests on mobile emulator
https://github.com/SAP/ui5-webcomponents/issues/2437
- [ ] Input's value handling (setting null and undefined, decimal value handling)

**Comment by boghyon** [comment]
Shouldn't the arrow buttons always be displayed on touch-enabled devices?
Here I explained why: https://github.com/SAP/openui5/issues/2826#issuecomment-592051853

**Comment by MarcusNotheis** [comment]
Maybe the SuccessFactors Dialog proposal should be added here as well? https://github.com/SAP/ui5-webcomponents-react/issues/1101

**Comment by ilhan007** [comment]
- [ ] "Alignment issue between Button, Link, Input and standard HTML elements" will be addressed by the teams

- all buttons  to be aligned - ui5-button, ui5-segmented-button, ui5-toggle-button, ui5-split-button
- all inputs to be aligned - ui5-(multi)input, ui5-(multi)combo-box, ui5-select, ui5-date(time)-picker

**Comment by vladitasev** [comment]
Closing as an old issue.

@MapTo0 If this part "Input's value handling (setting null and undefined, decimal value handling)" is still relevant, I'd suggest to create a separate issue for it.
