### ISSUE TITLE
ui5-table: to fulfil the ACC spec

### ISSUE THREAD

**Issue by pskelin** [SAP/ui5-webcomponents#441]
**Background*
The Table is one of the widely used components and we want to ensure it fulfills the ACC standard. The story is more like a "grooming" task, as it requires evaluating the current ACC state of the component.
Testing with VoiceOver on Mac shows that the reading is perfectly fine, as columns and rows are read out correctly, the current position and the total of columns and rows as well (f.e. 1 of 5 etc.). However we would like an expert to check the spec, test it with latest JAWS and confirm that is fine.

**Tasks**
- [x] check if all required ARIA attributes are in place
- [x] check column headers reading
- [x] check rows reading

**Comment by vladitasev** [comment]
Eli, can you please verify if this is still the case after the table refactoring.

**Comment by MapTo0** [comment]
https://github.com/SAP/ui5-webcomponents/pull/2534
