### ISSUE TITLE
Server-Side Rendering: initial research

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#6626]
### **Background**
`Server-Side Rendering (SSR)` is a technique in which the server generates the full HTML for a page on the server in response to navigation. This avoids additional round-trips for data fetching and templating on the client, since it’s handled before the browser gets a response(https://web.dev/rendering-on-the-web/). When it comes to web components, it means generating and serving the HTML of the web components, including shadow DOM and styles, before their JavaScript implementations have loaded and executed.

`SSR` can be used for a variety of reasons but performance is the most obvious one - some sites can render faster if they render static HTML first without waiting for JavaScript to load, then (optionally) load the page's JavaScript and hydrate the components.

### **Declarative Shadow DOM**
Historically, it has been difficult to use `Shadow DOM` in combination with `Server-Side Rendering` because there was no built-in way to express Shadow Roots in the server-generated HTML. There are also performance implications when attaching Shadow Roots to DOM elements that have already been rendered without them. This can cause layout shifting after the page has loaded, or temporarily show a flash of unstyled content while loading the Shadow Root's stylesheets.

[`Declarative Shadow DOM`](https://developer.chrome.com/articles/declarative-shadow-dom/) removes this limitation, bringing Shadow DOM to the server - it's a <template> element with a `shadowrootmode` attribute:

```html
<host-element>
  <template shadowrootmode="open">
    <slot></slot>
  </template>
  <h2>Light content</h2>
</host-element>
```
A template element with the shadowrootmode attribute is detected by the HTML parser and immediately applied as the shadow root of its parent element. Loading the pure HTML markup from the above sample results in the following DOM tree:

```html
<host-element>
  #shadow-root (open)
  <slot>
    ↳
    <h2>Light content</h2>
  </slot>
</host-element>
```

### **Declarative Shadow DOM Support**

- Chrome: supported
- Safari:  enabled by default in [Safari Technology Preview 162](https://webkit.org/blog/13703/release-notes-for-safari-technology-preview-162/)
- Firefox: not supported https://bugzilla.mozilla.org/show_bug.cgi?id=1712140

### **Feature Request**
As an application developer I would like to server-side my app, built UI5 Web Components could support some of the popular frameworks - like [Next.js](https://nextjs.org/).
https://github.com/SAP/ui5-webcomponents/issues/2240

### **Tasks**
- Research requirements of [Next.js](https://nextjs.org/) for the server-side rendering functionality
- Research [@lit-labs/ssr package](https://github.com/lit/lit/tree/main/packages/labs/ssr#readme) for server-side rendering Lit templates and components
- Share learning and list missing pieces in UI5 Web Components in SSR aspect to address as next steps

### **Additional Context**
Lit already have done some progress on the [topic](https://lit.dev/docs/ssr/overview/) and provides the [@lit-labs/ssr package](https://github.com/lit/lit/tree/main/packages/labs/ssr#readme) for server-side rendering Lit templates and components.
As we internally reuse lit templates, we have to look into that implementation and available integrations with server side frameworks- [KOA](https://koajs.com/), [Astro](https://astro.build/)

### **Related Issues**
https://github.com/SAP/ui5-webcomponents/issues/2240
https://github.com/SAP/ui5-webcomponents/issues/6192

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by cpf-hse** [comment]
@ilhan007 Any more details regarding this topic? 
Would be great to use the UI5 WCs in Frameworks like Sveltekit with all the advantages they provide.

**Comment by MarcusNotheis** [comment]
The [Declarative Shadow DOM proposal](https://github.com/whatwg/html/pull/5465) has now been merged into the HTML Spec and it looks like Firefox is going to [implement it soon](https://github.com/mozilla/standards-positions/issues/335#issuecomment-1714182997) as well. Are there any plans to implement this feature in the next couple of months?

**Comment by ilhan007** [comment]
Sub Tasks

- [ ] vladi: move async logic from processChildren to connectedCallback (see https://github.com/SAP/ui5-webcomponents/pull/9890)
- [ ] vladi: isSSR checks - productive cleanup
- [ ] refactor lifecycle so common steps are in single methods
- - [ ] constructor
- - [ ] connectedCallback
- - [ ] processChildren is used in ssr
- - [ ] updateAttributes
- - [ ] updateShadowRoot returns string
- [ ] pskelin: h-ssr - rethink where it is and integration with wrapper
- [x] ilhan: assets - import json works in NODEJS only with `{with:{type:"json"}})).default;`
- [ ] nayden: automated testing setup (test with client-side hydration)
- [x] nayden: UI5element hydrate - https://github.com/SAP/ui5-webcomponents/pull/11488
- [ ] ilhan: component specific use cases (button + select) - introduce isClientAPI
- [ ] ilhan: Extend DOM shims (children/childNodes) (or via better separation of SSR checks)
- [ ] i18n works, render with different theme
- [ ] styles - only inline
- - [ ] add links (CSP like)
- [ ] app integration
  - - how to insert all framework styles
  - - wrappers to trigger rendering
